import pandas as pd

def evaluate_stock(df, settings):
    """
    Evaluates the latest data point of the stock to generate a score and signal.
    """
    if df.empty:
        return 0, "NO DATA", "N/A"

    # Get the very last row as a Series of scalars
    # If df has multiple columns with the same name, this might still be a problem, 
    # but normally indicators add unique names.
    last_row = df.iloc[-1]
    
    # Column names generated by pandas_ta
    rsi_col = f"RSI_{settings['rsi_window']}"
    k_col = f"MACD_{settings['macd_fast']}_{settings['macd_slow']}_{settings['macd_signal']}"
    s_col = f"MACDs_{settings['macd_fast']}_{settings['macd_slow']}_{settings['macd_signal']}"
    ma_short_col = f"SMA_{settings['ma_short']}"
    ma_long_col = f"SMA_{settings['ma_long']}"

    # Default values
    score = 50
    signal = "WAIT"
    reason = []

    # Check RSI
    if rsi_col in last_row:
        # If last_row[rsi_col] is a Series (due to duplicate columns), take the first item
        val = last_row[rsi_col]
        rsi = val.iloc[0] if hasattr(val, 'iloc') else val
        
        if pd.isna(rsi):
            reason.append("RSI: No Data")
        elif rsi < 30:
            score += 20
            reason.append("RSI Oversold (<30)")
        elif rsi > 70:
            score -= 20
            reason.append("RSI Overbought (>70)")
        else:
            reason.append("RSI Neutral")

    # Check MACD
    if k_col in last_row and s_col in last_row:
        m_val = last_row[k_col]
        s_val = last_row[s_col]
        macd = m_val.iloc[0] if hasattr(m_val, 'iloc') else m_val
        signal_line = s_val.iloc[0] if hasattr(s_val, 'iloc') else s_val

        if not pd.isna(macd) and not pd.isna(signal_line):
            if macd > signal_line:
                score += 10
                reason.append("MACD Bullish Cross")
            else:
                score -= 10
                reason.append("MACD Bearish")

    # Check Trend (MA)
    if ma_short_col in last_row and ma_long_col in last_row:
        ms_val = last_row[ma_short_col]
        ml_val = last_row[ma_long_col]
        ma_s = ms_val.iloc[0] if hasattr(ms_val, 'iloc') else ms_val
        ma_l = ml_val.iloc[0] if hasattr(ml_val, 'iloc') else ml_val

        if not pd.isna(ma_s) and not pd.isna(ma_l):
            if ma_s > ma_l:
                 score += 10
                 reason.append("Golden Cross / Bullish Trend")
            else:
                 score -= 10
                 reason.append("Death Cross / Bearish Trend")


    # Final Signal Determination
    if score >= 70:
        signal = "BUY"
    elif score <= 30:
        signal = "SELL"
    else:
        signal = "WAIT"

    return score, signal, ", ".join(reason)
